services:
  # DCM4CHEE PACS
  dcm4chee:
    image: dcm4che/dcm4chee-arc-psql:5.26.0
    environment:
      - POSTGRES_DB=pacsdb
      - POSTGRES_USER=pacs
      - POSTGRES_PASSWORD=pacspass
      - DCM4CHEE_HOST=dcm4chee
      - WILDFLY_ADMIN_USER=admin
      - WILDFLY_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
      - "11112:11112"  # DICOM
    depends_on:
      - db
    networks:
      - pacs_network

  # Base de données PostgreSQL pour DCM4CHEE
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=pacsdb
      - POSTGRES_USER=pacs
      - POSTGRES_PASSWORD=pacspass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pacs_network

  # Apache NiFi
  nifi:
    image: apache/nifi:latest
    ports:
      - "8443:8443"
      - "8081:8081"
    environment:
      - NIFI_WEB_HTTP_PORT=8443
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=adminpassword
      - NIFI_WEB_HTTP_CORS_ENABLED=true
      - NIFI_WEB_HTTP_CORS_ALLOWED_HEADERS=*
      - NIFI_WEB_HTTP_CORS_ALLOWED_ORIGINS=*
      - NIFI_WEB_HTTP_CORS_ALLOWED_METHODS=GET,HEAD,POST,OPTIONS,PUT,DELETE
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_content:/opt/nifi/nifi-current/content_repository
      - nifi_database:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile:/opt/nifi/nifi-current/flowfile_repository
      - nifi_provenance:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
      - /Users/ilyasdahhou/Desktop/logs:/data/input
    networks:
      - pacs_network

  # Nginx comme proxy pour NiFi
  nginx:
    image: nginx:latest
    depends_on:
      - nifi
    ports:
      - "80:80"  # Nginx exposé sur le port 80
    volumes:
      - /Users/ilyasdahhou/Desktop/ecom-front/ecom/nginx.conf:/etc/nginx/nginx.conf  # Fichier de configuration Nginx
    networks:
      - pacs_network

volumes:
  postgres_data:
  nifi_conf:
  nifi_content:
  nifi_database:
  nifi_flowfile:
  nifi_provenance:
  nifi_state:

networks:
  pacs_network:
    driver: bridge
